import {
  ArrowRight,
  Award,
  BookOpen,
  Building,
  Calculator,
  Calendar,
  CalendarCheck,
  ClipboardCheck,
  ClipboardList,
  FileText,
  FlaskConical,
  GraduationCap,
  Heart,
  House,
  List,
  Medal,
  MessageCircleQuestionMark,
  PenLine,
  Phone,
  School,
  Shield,
  Sparkles,
  Target,
  Timer,
  Trophy,
  UserCheck,
  UserRound,
  Users,
  UsersRound,
  type LucideIcon,
} from "lucide-react";

export const iconMap = {
  "arrow-right": ArrowRight,
  award: Award,
  book: BookOpen,
  building: Building,
  calculator: Calculator,
  // Plain calendar (the policies hub, e.g. Cancellation and Refund Policy),
  // distinct from calendar-check below (the How It Works journey step).
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  doc: FileText,
  flask: FlaskConical,
  "graduation-cap": GraduationCap,
  heart: Heart,
  house: House,
  list: List,
  medal: Medal,
  "message-circle-question": MessageCircleQuestionMark,
  pen: PenLine,
  phone: Phone,
  school: School,
  shield: Shield,
  sparkles: Sparkles,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  "user-check": UserCheck,
  users: Users,
  "one-to-one": UserRound,
  "small-group": UsersRound,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof iconMap;

export function getIcon(key: string): LucideIcon {
  return (iconMap as Record<string, LucideIcon>)[key] ?? BookOpen;
}
