/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as BecomeATutorRouteImport } from './routes/become-a-tutor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnrolRouteImport } from './routes/enrol'
import { Route as ExamPrepRouteImport } from './routes/exam-prep'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HighSchoolRouteImport } from './routes/high-school'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HscMathsAdvancedRouteImport } from './routes/hsc-maths-advanced'
import { Route as OurMunksRouteImport } from './routes/our-munks'
import { Route as PrimaryEnglishRouteImport } from './routes/primary-english'
import { Route as PrimarySchoolRouteImport } from './routes/primary-school'
import { Route as SeniorSchoolRouteImport } from './routes/senior-school'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TutoringInChar123suburbSlugChar125RouteImport } from './routes/tutoring-in-{$suburbSlug}'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as PoliciesIndexRouteImport } from './routes/policies.index'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as BlogPagePageRouteImport } from './routes/blog.page.$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATutorRoute = BecomeATutorRouteImport.update({
  id: '/become-a-tutor',
  path: '/become-a-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrolRoute = EnrolRouteImport.update({
  id: '/enrol',
  path: '/enrol',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPrepRoute = ExamPrepRouteImport.update({
  id: '/exam-prep',
  path: '/exam-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HighSchoolRoute = HighSchoolRouteImport.update({
  id: '/high-school',
  path: '/high-school',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HscMathsAdvancedRoute = HscMathsAdvancedRouteImport.update({
  id: '/hsc-maths-advanced',
  path: '/hsc-maths-advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const OurMunksRoute = OurMunksRouteImport.update({
  id: '/our-munks',
  path: '/our-munks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaryEnglishRoute = PrimaryEnglishRouteImport.update({
  id: '/primary-english',
  path: '/primary-english',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimarySchoolRoute = PrimarySchoolRouteImport.update({
  id: '/primary-school',
  path: '/primary-school',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorSchoolRoute = SeniorSchoolRouteImport.update({
  id: '/senior-school',
  path: '/senior-school',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoringInChar123suburbSlugChar125Route =
  TutoringInChar123suburbSlugChar125RouteImport.update({
    id: '/tutoring-in-{$suburbSlug}',
    path: '/tutoring-in-{$suburbSlug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPagePageRoute = BlogPagePageRouteImport.update({
  id: '/blog/page/$page',
  path: '/blog/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/become-a-tutor': typeof BecomeATutorRoute
  '/contact': typeof ContactRoute
  '/enrol': typeof EnrolRoute
  '/exam-prep': typeof ExamPrepRoute
  '/faq': typeof FaqRoute
  '/high-school': typeof HighSchoolRoute
  '/how-it-works': typeof HowItWorksRoute
  '/hsc-maths-advanced': typeof HscMathsAdvancedRoute
  '/our-munks': typeof OurMunksRoute
  '/primary-english': typeof PrimaryEnglishRoute
  '/primary-school': typeof PrimarySchoolRoute
  '/senior-school': typeof SeniorSchoolRoute
  '/testimonials': typeof TestimonialsRoute
  '/tutoring-in-{$suburbSlug}': typeof TutoringInChar123suburbSlugChar125Route
  '/blog/$slug': typeof BlogSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/become-a-tutor': typeof BecomeATutorRoute
  '/contact': typeof ContactRoute
  '/enrol': typeof EnrolRoute
  '/exam-prep': typeof ExamPrepRoute
  '/faq': typeof FaqRoute
  '/high-school': typeof HighSchoolRoute
  '/how-it-works': typeof HowItWorksRoute
  '/hsc-maths-advanced': typeof HscMathsAdvancedRoute
  '/our-munks': typeof OurMunksRoute
  '/primary-english': typeof PrimaryEnglishRoute
  '/primary-school': typeof PrimarySchoolRoute
  '/senior-school': typeof SeniorSchoolRoute
  '/testimonials': typeof TestimonialsRoute
  '/tutoring-in-{$suburbSlug}': typeof TutoringInChar123suburbSlugChar125Route
  '/blog/$slug': typeof BlogSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/become-a-tutor': typeof BecomeATutorRoute
  '/contact': typeof ContactRoute
  '/enrol': typeof EnrolRoute
  '/exam-prep': typeof ExamPrepRoute
  '/faq': typeof FaqRoute
  '/high-school': typeof HighSchoolRoute
  '/how-it-works': typeof HowItWorksRoute
  '/hsc-maths-advanced': typeof HscMathsAdvancedRoute
  '/our-munks': typeof OurMunksRoute
  '/primary-english': typeof PrimaryEnglishRoute
  '/primary-school': typeof PrimarySchoolRoute
  '/senior-school': typeof SeniorSchoolRoute
  '/testimonials': typeof TestimonialsRoute
  '/tutoring-in-{$suburbSlug}': typeof TutoringInChar123suburbSlugChar125Route
  '/blog/$slug': typeof BlogSlugRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/become-a-tutor'
    | '/contact'
    | '/enrol'
    | '/exam-prep'
    | '/faq'
    | '/high-school'
    | '/how-it-works'
    | '/hsc-maths-advanced'
    | '/our-munks'
    | '/primary-english'
    | '/primary-school'
    | '/senior-school'
    | '/testimonials'
    | '/tutoring-in-{$suburbSlug}'
    | '/blog/$slug'
    | '/policies/$slug'
    | '/topics/$slug'
    | '/blog/'
    | '/locations/'
    | '/policies/'
    | '/blog/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/become-a-tutor'
    | '/contact'
    | '/enrol'
    | '/exam-prep'
    | '/faq'
    | '/high-school'
    | '/how-it-works'
    | '/hsc-maths-advanced'
    | '/our-munks'
    | '/primary-english'
    | '/primary-school'
    | '/senior-school'
    | '/testimonials'
    | '/tutoring-in-{$suburbSlug}'
    | '/blog/$slug'
    | '/policies/$slug'
    | '/topics/$slug'
    | '/blog'
    | '/locations'
    | '/policies'
    | '/blog/page/$page'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/become-a-tutor'
    | '/contact'
    | '/enrol'
    | '/exam-prep'
    | '/faq'
    | '/high-school'
    | '/how-it-works'
    | '/hsc-maths-advanced'
    | '/our-munks'
    | '/primary-english'
    | '/primary-school'
    | '/senior-school'
    | '/testimonials'
    | '/tutoring-in-{$suburbSlug}'
    | '/blog/$slug'
    | '/policies/$slug'
    | '/topics/$slug'
    | '/blog/'
    | '/locations/'
    | '/policies/'
    | '/blog/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  BecomeATutorRoute: typeof BecomeATutorRoute
  ContactRoute: typeof ContactRoute
  EnrolRoute: typeof EnrolRoute
  ExamPrepRoute: typeof ExamPrepRoute
  FaqRoute: typeof FaqRoute
  HighSchoolRoute: typeof HighSchoolRoute
  HowItWorksRoute: typeof HowItWorksRoute
  HscMathsAdvancedRoute: typeof HscMathsAdvancedRoute
  OurMunksRoute: typeof OurMunksRoute
  PrimaryEnglishRoute: typeof PrimaryEnglishRoute
  PrimarySchoolRoute: typeof PrimarySchoolRoute
  SeniorSchoolRoute: typeof SeniorSchoolRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TutoringInChar123suburbSlugChar125Route: typeof TutoringInChar123suburbSlugChar125Route
  BlogSlugRoute: typeof BlogSlugRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  BlogPagePageRoute: typeof BlogPagePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-tutor': {
      id: '/become-a-tutor'
      path: '/become-a-tutor'
      fullPath: '/become-a-tutor'
      preLoaderRoute: typeof BecomeATutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrol': {
      id: '/enrol'
      path: '/enrol'
      fullPath: '/enrol'
      preLoaderRoute: typeof EnrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-prep': {
      id: '/exam-prep'
      path: '/exam-prep'
      fullPath: '/exam-prep'
      preLoaderRoute: typeof ExamPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-school': {
      id: '/high-school'
      path: '/high-school'
      fullPath: '/high-school'
      preLoaderRoute: typeof HighSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hsc-maths-advanced': {
      id: '/hsc-maths-advanced'
      path: '/hsc-maths-advanced'
      fullPath: '/hsc-maths-advanced'
      preLoaderRoute: typeof HscMathsAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-munks': {
      id: '/our-munks'
      path: '/our-munks'
      fullPath: '/our-munks'
      preLoaderRoute: typeof OurMunksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary-english': {
      id: '/primary-english'
      path: '/primary-english'
      fullPath: '/primary-english'
      preLoaderRoute: typeof PrimaryEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary-school': {
      id: '/primary-school'
      path: '/primary-school'
      fullPath: '/primary-school'
      preLoaderRoute: typeof PrimarySchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior-school': {
      id: '/senior-school'
      path: '/senior-school'
      fullPath: '/senior-school'
      preLoaderRoute: typeof SeniorSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoring-in-{$suburbSlug}': {
      id: '/tutoring-in-{$suburbSlug}'
      path: '/tutoring-in-{$suburbSlug}'
      fullPath: '/tutoring-in-{$suburbSlug}'
      preLoaderRoute: typeof TutoringInChar123suburbSlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/page/$page': {
      id: '/blog/page/$page'
      path: '/blog/page/$page'
      fullPath: '/blog/page/$page'
      preLoaderRoute: typeof BlogPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  BecomeATutorRoute: BecomeATutorRoute,
  ContactRoute: ContactRoute,
  EnrolRoute: EnrolRoute,
  ExamPrepRoute: ExamPrepRoute,
  FaqRoute: FaqRoute,
  HighSchoolRoute: HighSchoolRoute,
  HowItWorksRoute: HowItWorksRoute,
  HscMathsAdvancedRoute: HscMathsAdvancedRoute,
  OurMunksRoute: OurMunksRoute,
  PrimaryEnglishRoute: PrimaryEnglishRoute,
  PrimarySchoolRoute: PrimarySchoolRoute,
  SeniorSchoolRoute: SeniorSchoolRoute,
  TestimonialsRoute: TestimonialsRoute,
  TutoringInChar123suburbSlugChar125Route:
    TutoringInChar123suburbSlugChar125Route,
  BlogSlugRoute: BlogSlugRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  BlogPagePageRoute: BlogPagePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
